// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Pegasus.Data
{
    public class ApiScopesConfiguration : IEntityTypeConfiguration<ApiScopes>
    {
        public void Configure(EntityTypeBuilder<ApiScopes> entity)
        {
            entity.HasIndex(e => e.ApiResourceId);

            entity.HasIndex(e => e.Name)
                .IsUnique();
        }
    }
}
