// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Pegasus.Data
{
    public class IdentityPropertiesConfiguration : IEntityTypeConfiguration<IdentityProperties>
    {
        public void Configure(EntityTypeBuilder<IdentityProperties> entity)
        {
            entity.HasIndex(e => e.IdentityResourceId);
        }
    }
}
