// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pegasus.Data
{
    public partial class IsolationCenters
    {
        public IsolationCenters()
        {
            PersonProfile = new HashSet<PersonProfile>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "text")]
        public string CenterName { get; set; }
        [Column(TypeName = "text")]
        public string Address { get; set; }
        [Column(TypeName = "text")]
        public string ContactNo { get; set; }

        [InverseProperty("IsolationCenterNavigation")]
        public virtual ICollection<PersonProfile> PersonProfile { get; set; }
    }
}