// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pegasus.Data
{
    public partial class PersonHistory
    {
        [Key]
        public int Id { get; set; }
        public int? PersonProfileid { get; set; }
        [Column(TypeName = "text")]
        public string Remarks { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCreated { get; set; }
        public int? CreatedBy { get; set; }

        [ForeignKey(nameof(PersonProfileid))]
        [InverseProperty("PersonHistory")]
        public virtual PersonProfile PersonProfile { get; set; }
    }
}