// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Pegasus.Data
{
    public class PersonHistoryConfiguration : IEntityTypeConfiguration<PersonHistory>
    {
        public void Configure(EntityTypeBuilder<PersonHistory> entity)
        {
            entity.HasOne(d => d.PersonProfile)
                .WithMany(p => p.PersonHistory)
                .HasForeignKey(d => d.PersonProfileid)
                .HasConstraintName("FK_PersonHistory_PersonProfile");
        }
    }
}
