// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Pegasus.Data
{
    public class TenantsConfiguration : IEntityTypeConfiguration<Tenants>
    {
        public void Configure(EntityTypeBuilder<Tenants> entity)
        {
            entity.HasIndex(e => e.OwnerUserId)
                .IsUnique();

            entity.HasOne(d => d.OwnerUser)
                .WithOne(p => p.Tenants)
                .HasForeignKey<Tenants>(d => d.OwnerUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        }
    }
}
