// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pegasus.Data
{
    public partial class Tenants
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(128)]
        public string Title { get; set; }
        public Guid OwnerUserId { get; set; }

        [ForeignKey(nameof(OwnerUserId))]
        [InverseProperty(nameof(AspNetUsers.Tenants))]
        public virtual AspNetUsers OwnerUser { get; set; }
    }
}