// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pegasus.Data
{
    public partial class Users
    {
        [Key]
        public int UserId { get; set; }
        public string Username { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string ContactNo { get; set; }
        public string ConfirmPass { get; set; }
        public int? RoleId { get; set; }

        [ForeignKey(nameof(RoleId))]
        [InverseProperty(nameof(UserRole.Users))]
        public virtual UserRole Role { get; set; }
    }
}